package POJOs;
// Generated 21/10/2024 11:49:32 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Compras generated by hbm2java
 */
public class Compras  implements java.io.Serializable {


     private int numeroCompra;
     private Proveedores proveedores;
     private Usuarios Usuarios;
     private boolean estadoCompra;
     private Date fechaCompra;
     private Set<DetalleCompra> detalleCompras = new HashSet<DetalleCompra>(0);

    public Compras() {
    }

	
    public Compras(int numeroCompra, Proveedores proveedores, Usuarios Usuarios, boolean estadoCompra, Date fechaCompra) {
        this.numeroCompra = numeroCompra;
        this.proveedores = proveedores;
        this.Usuarios = Usuarios;
        this.estadoCompra = estadoCompra;
        this.fechaCompra = fechaCompra;
    }
    public Compras(int numeroCompra, Proveedores proveedores, Usuarios Usuarios, boolean estadoCompra, Date fechaCompra, Set<DetalleCompra> detalleCompras) {
       this.numeroCompra = numeroCompra;
       this.proveedores = proveedores;
       this.Usuarios = Usuarios;
       this.estadoCompra = estadoCompra;
       this.fechaCompra = fechaCompra;
       this.detalleCompras = detalleCompras;
    }
   
    public int getNumeroCompra() {
        return this.numeroCompra;
    }
    
    public void setNumeroCompra(int numeroCompra) {
        this.numeroCompra = numeroCompra;
    }
    public Proveedores getProveedores() {
        return this.proveedores;
    }
    
    public void setProveedores(Proveedores proveedores) {
        this.proveedores = proveedores;
    }
    public Usuarios getUsuarios() {
        return this.Usuarios;
    }
    
    public void setUsuarios(Usuarios Usuarios) {
        this.Usuarios = Usuarios;
    }
    public boolean isEstadoCompra() {
        return this.estadoCompra;
    }
    
    public void setEstadoCompra(boolean estadoCompra) {
        this.estadoCompra = estadoCompra;
    }
    public Date getFechaCompra() {
        return this.fechaCompra;
    }
    
    public void setFechaCompra(Date fechaCompra) {
        this.fechaCompra = fechaCompra;
    }
    public Set<DetalleCompra> getDetalleCompras() {
        return this.detalleCompras;
    }
    
    public void setDetalleCompras(Set<DetalleCompra> detalleCompras) {
        this.detalleCompras = detalleCompras;
    }




}


