package POJOs;
// Generated 23/10/2024 09:26:17 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Productos generated by hbm2java
 */
public class Productos  implements java.io.Serializable {


     private Integer idProducto;
     private Categorias categorias;
     private String nombreProducto;
     private String descripcionProducto;
     private float existencia;
     private float precioCosto;
     private float precioVenta;
     private Set<DetalleVenta> detalleVentas = new HashSet<DetalleVenta>(0);
     private Set<DetalleCompra> detalleCompras = new HashSet<DetalleCompra>(0);

    public Productos() {
    }

	
    public Productos(Categorias categorias, String nombreProducto, String descripcionProducto, float existencia, float precioCosto, float precioVenta) {
        this.categorias = categorias;
        this.nombreProducto = nombreProducto;
        this.descripcionProducto = descripcionProducto;
        this.existencia = existencia;
        this.precioCosto = precioCosto;
        this.precioVenta = precioVenta;
    }
    public Productos(Categorias categorias, String nombreProducto, String descripcionProducto, float existencia, float precioCosto, float precioVenta, Set<DetalleVenta> detalleVentas, Set<DetalleCompra> detalleCompras) {
       this.categorias = categorias;
       this.nombreProducto = nombreProducto;
       this.descripcionProducto = descripcionProducto;
       this.existencia = existencia;
       this.precioCosto = precioCosto;
       this.precioVenta = precioVenta;
       this.detalleVentas = detalleVentas;
       this.detalleCompras = detalleCompras;
    }
   
    public Integer getIdProducto() {
        return this.idProducto;
    }
    
    public void setIdProducto(Integer idProducto) {
        this.idProducto = idProducto;
    }
    public Categorias getCategorias() {
        return this.categorias;
    }
    
    public void setCategorias(Categorias categorias) {
        this.categorias = categorias;
    }
    public String getNombreProducto() {
        return this.nombreProducto;
    }
    
    public void setNombreProducto(String nombreProducto) {
        this.nombreProducto = nombreProducto;
    }
    public String getDescripcionProducto() {
        return this.descripcionProducto;
    }
    
    public void setDescripcionProducto(String descripcionProducto) {
        this.descripcionProducto = descripcionProducto;
    }
    public float getExistencia() {
        return this.existencia;
    }
    
    public void setExistencia(float existencia) {
        this.existencia = existencia;
    }
    public float getPrecioCosto() {
        return this.precioCosto;
    }
    
    public void setPrecioCosto(float precioCosto) {
        this.precioCosto = precioCosto;
    }
    public float getPrecioVenta() {
        return this.precioVenta;
    }
    
    public void setPrecioVenta(float precioVenta) {
        this.precioVenta = precioVenta;
    }
    public Set<DetalleVenta> getDetalleVentas() {
        return this.detalleVentas;
    }
    
    public void setDetalleVentas(Set<DetalleVenta> detalleVentas) {
        this.detalleVentas = detalleVentas;
    }
    public Set<DetalleCompra> getDetalleCompras() {
        return this.detalleCompras;
    }
    
    public void setDetalleCompras(Set<DetalleCompra> detalleCompras) {
        this.detalleCompras = detalleCompras;
    }




}


