package POJOs;
// Generated 23/10/2024 09:26:17 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Proveedores generated by hbm2java
 */
public class Proveedores  implements java.io.Serializable {


     private Integer nitProveedor;
     private boolean estadoProveedor;
     private String nombreProveedor;
     private String direccionProveedor;
     private String telefonoProveedor;
     private Set<Compras> comprases = new HashSet<Compras>(0);

    public Proveedores() {
    }

	
    public Proveedores(boolean estadoProveedor, String nombreProveedor, String direccionProveedor, String telefonoProveedor) {
        this.estadoProveedor = estadoProveedor;
        this.nombreProveedor = nombreProveedor;
        this.direccionProveedor = direccionProveedor;
        this.telefonoProveedor = telefonoProveedor;
    }
    public Proveedores(boolean estadoProveedor, String nombreProveedor, String direccionProveedor, String telefonoProveedor, Set<Compras> comprases) {
       this.estadoProveedor = estadoProveedor;
       this.nombreProveedor = nombreProveedor;
       this.direccionProveedor = direccionProveedor;
       this.telefonoProveedor = telefonoProveedor;
       this.comprases = comprases;
    }
   
    public Integer getNitProveedor() {
        return this.nitProveedor;
    }
    
    public void setNitProveedor(Integer nitProveedor) {
        this.nitProveedor = nitProveedor;
    }
    public boolean isEstadoProveedor() {
        return this.estadoProveedor;
    }
    
    public void setEstadoProveedor(boolean estadoProveedor) {
        this.estadoProveedor = estadoProveedor;
    }
    public String getNombreProveedor() {
        return this.nombreProveedor;
    }
    
    public void setNombreProveedor(String nombreProveedor) {
        this.nombreProveedor = nombreProveedor;
    }
    public String getDireccionProveedor() {
        return this.direccionProveedor;
    }
    
    public void setDireccionProveedor(String direccionProveedor) {
        this.direccionProveedor = direccionProveedor;
    }
    public String getTelefonoProveedor() {
        return this.telefonoProveedor;
    }
    
    public void setTelefonoProveedor(String telefonoProveedor) {
        this.telefonoProveedor = telefonoProveedor;
    }
    public Set<Compras> getComprases() {
        return this.comprases;
    }
    
    public void setComprases(Set<Compras> comprases) {
        this.comprases = comprases;
    }




}


