package POJOs;
// Generated 25/10/2024 02:38:30 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Usuarios generated by hbm2java
 */
public class Usuarios  implements java.io.Serializable {


     private Integer idUsuario;
     private boolean estadoUsuario;
     private String nombreUsuario;
     private String cargoUsuario;
     private String contraseniaUsuario;
     private Set<Ventas> ventases = new HashSet<Ventas>(0);
     private Set<Compras> comprases = new HashSet<Compras>(0);

    public Usuarios() {
    }

	
    public Usuarios(boolean estadoUsuario, String nombreUsuario, String cargoUsuario, String contraseniaUsuario) {
        this.estadoUsuario = estadoUsuario;
        this.nombreUsuario = nombreUsuario;
        this.cargoUsuario = cargoUsuario;
        this.contraseniaUsuario = contraseniaUsuario;
    }
    public Usuarios(boolean estadoUsuario, String nombreUsuario, String cargoUsuario, String contraseniaUsuario, Set<Ventas> ventases, Set<Compras> comprases) {
       this.estadoUsuario = estadoUsuario;
       this.nombreUsuario = nombreUsuario;
       this.cargoUsuario = cargoUsuario;
       this.contraseniaUsuario = contraseniaUsuario;
       this.ventases = ventases;
       this.comprases = comprases;
    }
   
    public Integer getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(Integer idUsuario) {
        this.idUsuario = idUsuario;
    }
    public boolean isEstadoUsuario() {
        return this.estadoUsuario;
    }
    
    public void setEstadoUsuario(boolean estadoUsuario) {
        this.estadoUsuario = estadoUsuario;
    }
    public String getNombreUsuario() {
        return this.nombreUsuario;
    }
    
    public void setNombreUsuario(String nombreUsuario) {
        this.nombreUsuario = nombreUsuario;
    }
    public String getCargoUsuario() {
        return this.cargoUsuario;
    }
    
    public void setCargoUsuario(String cargoUsuario) {
        this.cargoUsuario = cargoUsuario;
    }
    public String getContraseniaUsuario() {
        return this.contraseniaUsuario;
    }
    
    public void setContraseniaUsuario(String contraseniaUsuario) {
        this.contraseniaUsuario = contraseniaUsuario;
    }
    public Set<Ventas> getVentases() {
        return this.ventases;
    }
    
    public void setVentases(Set<Ventas> ventases) {
        this.ventases = ventases;
    }
    public Set<Compras> getComprases() {
        return this.comprases;
    }
    
    public void setComprases(Set<Compras> comprases) {
        this.comprases = comprases;
    }




}


