package POJOs;
// Generated 21/10/2024 11:49:32 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Usuarioss generated by hbm2java
 */
public class Usuarios  implements java.io.Serializable {


     private int idUsuarios;
     private boolean estadoUsuarios;
     private String nombreUsuarios;
     private String cargoUsuarios;
     private String contraseniaUsuarios;
     private Set<Ventas> ventases = new HashSet<Ventas>(0);
     private Set<Compras> comprases = new HashSet<Compras>(0);

    public Usuarios() {
    }

	
    public Usuarios(int idUsuarios, boolean estadoUsuarios, String nombreUsuarios, String cargoUsuarios, String contraseniaUsuarios) {
        this.idUsuarios = idUsuarios;
        this.estadoUsuarios = estadoUsuarios;
        this.nombreUsuarios = nombreUsuarios;
        this.cargoUsuarios = cargoUsuarios;
        this.contraseniaUsuarios = contraseniaUsuarios;
    }
    public Usuarios(int idUsuarios, boolean estadoUsuarios, String nombreUsuarios, String cargoUsuarios, String contraseniaUsuarios, Set<Ventas> ventases, Set<Compras> comprases) {
       this.idUsuarios = idUsuarios;
       this.estadoUsuarios = estadoUsuarios;
       this.nombreUsuarios = nombreUsuarios;
       this.cargoUsuarios = cargoUsuarios;
       this.contraseniaUsuarios = contraseniaUsuarios;
       this.ventases = ventases;
       this.comprases = comprases;
    }
   
    public int getIdUsuarios() {
        return this.idUsuarios;
    }
    
    public void setIdUsuarios(int idUsuarios) {
        this.idUsuarios = idUsuarios;
    }
    public boolean isEstadoUsuarios() {
        return this.estadoUsuarios;
    }
    
    public void setEstadoUsuarios(boolean estadoUsuarios) {
        this.estadoUsuarios = estadoUsuarios;
    }
    public String getNombreUsuarios() {
        return this.nombreUsuarios;
    }
    
    public void setNombreUsuarios(String nombreUsuarios) {
        this.nombreUsuarios = nombreUsuarios;
    }
    public String getCargoUsuarios() {
        return this.cargoUsuarios;
    }
    
    public void setCargoUsuarios(String cargoUsuarios) {
        this.cargoUsuarios = cargoUsuarios;
    }
    public String getContraseniaUsuarios() {
        return this.contraseniaUsuarios;
    }
    
    public void setContraseniaUsuarios(String contraseniaUsuarios) {
        this.contraseniaUsuarios = contraseniaUsuarios;
    }
    public Set<Ventas> getVentases() {
        return this.ventases;
    }
    
    public void setVentases(Set<Ventas> ventases) {
        this.ventases = ventases;
    }
    public Set<Compras> getComprases() {
        return this.comprases;
    }
    
    public void setComprases(Set<Compras> comprases) {
        this.comprases = comprases;
    }




}


