package POJOs;
// Generated 21/10/2024 11:49:32 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Ventas generated by hbm2java
 */
public class Ventas  implements java.io.Serializable {


     private int numeroVenta;
     private Clientes clientes;
     private Usuarios Usuarios;
     private boolean estadoVenta;
     private Date fechaVenta;
     private Set<DetalleVenta> detalleVentas = new HashSet<DetalleVenta>(0);

    public Ventas() {
    }

	
    public Ventas(int numeroVenta, Clientes clientes, Usuarios Usuarios, boolean estadoVenta, Date fechaVenta) {
        this.numeroVenta = numeroVenta;
        this.clientes = clientes;
        this.Usuarios = Usuarios;
        this.estadoVenta = estadoVenta;
        this.fechaVenta = fechaVenta;
    }
    public Ventas(int numeroVenta, Clientes clientes, Usuarios Usuarios, boolean estadoVenta, Date fechaVenta, Set<DetalleVenta> detalleVentas) {
       this.numeroVenta = numeroVenta;
       this.clientes = clientes;
       this.Usuarios = Usuarios;
       this.estadoVenta = estadoVenta;
       this.fechaVenta = fechaVenta;
       this.detalleVentas = detalleVentas;
    }
   
    public int getNumeroVenta() {
        return this.numeroVenta;
    }
    
    public void setNumeroVenta(int numeroVenta) {
        this.numeroVenta = numeroVenta;
    }
    public Clientes getClientes() {
        return this.clientes;
    }
    
    public void setClientes(Clientes clientes) {
        this.clientes = clientes;
    }
    public Usuarios getUsuarioss() {
        return this.Usuarios;
    }
    
    public void setUsuarioss(Usuarios Usuarioss) {
        this.Usuarios = Usuarioss;
    }
    public boolean isEstadoVenta() {
        return this.estadoVenta;
    }
    
    public void setEstadoVenta(boolean estadoVenta) {
        this.estadoVenta = estadoVenta;
    }
    public Date getFechaVenta() {
        return this.fechaVenta;
    }
    
    public void setFechaVenta(Date fechaVenta) {
        this.fechaVenta = fechaVenta;
    }
    public Set<DetalleVenta> getDetalleVentas() {
        return this.detalleVentas;
    }
    
    public void setDetalleVentas(Set<DetalleVenta> detalleVentas) {
        this.detalleVentas = detalleVentas;
    }




}


